
import { Signal } from './types';

export const ROLES = ['Exec', 'Operator', 'Product'] as const;
export const INDUSTRIES = ['Auto', 'Logistics', 'Retail', 'Manufacturing', 'Finance', 'Healthcare', 'SaaS'] as const;

export const SIGNALS: Signal[] = [
  {
    id: 'problem-gravity',
    index: '01',
    title: 'PROBLEM GRAVITY',
    truth: 'The measurable capability of a specific problem to pull resources, attention, and urgency into its orbit naturally.',
    relatedIds: ['latency-sensitivity', 'outcome-binding']
  },
  {
    id: 'friction-index',
    index: '02',
    title: 'FRICTION INDEX',
    truth: 'The drag coefficient of your organizational workflows; where velocity goes to die.',
    relatedIds: ['tool-friction', 'workflow-inertia']
  },
  {
    id: 'decision-density',
    index: '03',
    title: 'DECISION DENSITY',
    truth: 'The volume of high-stakes choices required per unit of execution time. AI should lower this, not raise it.',
    relatedIds: ['human-in-loop-load', 'second-brain-leverage']
  },
  {
    id: 'trust-surface-area',
    index: '04',
    title: 'TRUST SURFACE AREA',
    truth: 'The exposure level where human intervention is mandatory to maintain stakeholder confidence.',
    relatedIds: ['human-in-loop-load', 'agent-ownership', 'failure-visibility']
  },
  {
    id: 'latency-sensitivity',
    index: '05',
    title: 'LATENCY SENSITIVITY',
    truth: 'The precise cost of delay. In some loops, speed is the only feature that matters.',
    relatedIds: ['problem-gravity', 'outcome-compounding']
  },
  {
    id: 'context-decay',
    index: '06',
    title: 'CONTEXT DECAY',
    truth: 'The rate at which information becomes irrelevant or toxic as it moves through the organization.',
    relatedIds: ['state-drift', 'knowledge-half-life']
  },
  {
    id: 'tool-friction',
    index: '07',
    title: 'TOOL FRICTION',
    truth: 'The cognitive load required to switch between the instruments of work.',
    relatedIds: ['friction-index', 'integration-depth']
  },
  {
    id: 'human-in-loop-load',
    index: '08',
    title: 'HITL LOAD',
    truth: 'The tax paid in human attention to correct, verify, or steer automated systems.',
    relatedIds: ['trust-surface-area', 'decision-density']
  },
  {
    id: 'failure-visibility',
    index: '09',
    title: 'FAILURE VISIBILITY',
    truth: 'How obvious it is when a system breaks. Silent failures are the highest risk.',
    relatedIds: ['trust-surface-area', 'state-drift']
  },
  {
    id: 'state-drift',
    index: '10',
    title: 'STATE DRIFT',
    truth: 'The divergence between the system’s map of reality and the territory itself.',
    relatedIds: ['context-decay', 'failure-visibility']
  },
  {
    id: 'outcome-binding',
    index: '11',
    title: 'OUTCOME BINDING',
    truth: 'How tightly an AI initiative is coupled to a P&L result versus a vanity metric.',
    relatedIds: ['outcome-compounding', 'campground-vs-bomb-factory']
  },
  {
    id: 'workflow-inertia',
    index: '12',
    title: 'WORKFLOW INERTIA',
    truth: 'The resistance of an existing process to being reshaped by intelligence.',
    relatedIds: ['friction-index', 'adoption-velocity']
  },
  {
    id: 'knowledge-half-life',
    index: '13',
    title: 'KNOWLEDGE HALF-LIFE',
    truth: 'The speed at which your proprietary insight becomes a commodity.',
    relatedIds: ['second-brain-leverage', 'context-decay']
  },
  {
    id: 'agent-ownership',
    index: '14',
    title: 'AGENT OWNERSHIP',
    truth: 'Who owns the outcome when the agent acts? The defining legal boundary of the next decade.',
    relatedIds: ['trust-surface-area', 'outcome-binding']
  },
  {
    id: 'integration-depth',
    index: '15',
    title: 'INTEGRATION DEPTH',
    truth: 'Is the AI a wrapper, or is it woven into the substrate of the business logic?',
    relatedIds: ['tool-friction', 'campground-vs-bomb-factory']
  },
  {
    id: 'campground-vs-bomb-factory',
    index: '16',
    title: 'CAMPGROUND VS FACTORY',
    truth: 'Are you building for safety and comfort, or for maximum explosive output?',
    relatedIds: ['integration-depth', 'outcome-binding']
  },
  {
    id: 'signal-to-noise',
    index: '17',
    title: 'SIGNAL-TO-NOISE',
    truth: 'The ratio of actionable insight to raw data generated by your systems.',
    relatedIds: ['second-brain-leverage', 'decision-density']
  },
  {
    id: 'adoption-velocity',
    index: '18',
    title: 'ADOPTION VELOCITY',
    truth: 'The time it takes for a new capability to become the default way of working.',
    relatedIds: ['workflow-inertia', 'friction-index']
  },
  {
    id: 'second-brain-leverage',
    index: '19',
    title: 'SECOND-BRAIN LEVERAGE',
    truth: 'The multiplier effect of offloading memory and synthesis to external substrates.',
    relatedIds: ['knowledge-half-life', 'signal-to-noise']
  },
  {
    id: 'outcome-compounding',
    index: '20',
    title: 'OUTCOME COMPOUNDING',
    truth: 'When one efficiency gain automatically triggers the next, creating a flywheel.',
    relatedIds: ['outcome-binding', 'latency-sensitivity']
  },
];
